### ISSUE TITLE
Please don't bundle evil-tests.el

### ISSUE THREAD

**Issue by tarsius** [edkolev/evil-goggles#15]
If you do then someone who wants to test `evil` itself might end up your bundled copy instead. That's a problem because your copy already isn't identical anymore and even if you updated it, it would probably get out-of-date again.

Can't you just assume that `evil` including `evil-tests` is available? Or else download it without checking it into the `evil-goggles` repository (it seems there is already code to do that)?

**Comment by edkolev** [comment]
Sure, I'll remove the bundled file. I didn't want to bundle it in the first place, I did so because the file had to be tweaked a bit, otherwise the automated tests would SEG fault occasionally.

My initial approach was to wget the file from evil's repo, but, as I said, it didn't work out.

I'll look into other options.

BTW I'm yet again amazed by the emacs community. Thank you! I just backed your kickstarter campaign, hope you reach the goal.

**Comment by tarsius** [comment]
Thanks to you too!
