### ISSUE TITLE
Evil goggles ignores faces :foreground property

### ISSUE THREAD

**Issue by gilbertw1** [edkolev/evil-goggles#16]
Hi, I recently noticed that evil-goggles stopped changing the font face foreground when displaying visual hints. I used git-bisect to figure out that the first commit exhibiting this behavior is: f79c03ba6274ba61d1301b793122dab6fff8da53.

Before: f79c03ba6274ba61d1301b793122dab6fff8da53
http://drop.bryan.sh/6BGfwzSb4A.mp4

After f79c03ba6274ba61d1301b793122dab6fff8da53:
http://drop.bryan.sh/x5MrWktqkC.mp4

You can see from the two quick screencasts that the `:foreground` property is being ignored on all of the `evil-goggles-*` faces. If I add a `:background` property to each of my fonts, I can see that the background color does change properly, just not the foreground.

Here's my configuration for reference:

```emacs-lisp
;; Override evil googles colors
(custom-set-faces
 '(evil-goggles-delete-face           ((t (:foreground "#ff6c6b"))))
 '(evil-goggles-paste-face            ((t (:foreground "#98be65"))))
 '(evil-goggles-yank-face             ((t (:foreground "#51afef"))))
 '(evil-goggles-undo-redo-remove-face ((t (:foreground "#ff6c6b"))))
 '(evil-goggles-undo-redo-add-face    ((t (:foreground "#98be65"))))
 '(evil-goggles-undo-redo-change-face ((t (:foreground "#51afef")))))
```

Thanks!

**Comment by edkolev** [comment]
I made this change because pulsing (via pulse.el) works with the background only. As a result both with and without pulsing the visual hint looks the same.

 I'll think about a longterm solution (maybe re-implement pulsing instead of using pulse.el and its background-only limitation). But for now I'll restore the old behaviour and let you know.

Thanks for the detailed report.

**Comment by gilbertw1** [comment]
Awesome, thanks for the quick response!
