### ISSUE TITLE
Built-in face for evil-goggles

### ISSUE THREAD

**Issue by 0rdy** [edkolev/evil-goggles#2]
A large number of Emacs packages, which provide an appearance enchantment, have their own face. For example, hl-line mode, nlinum, custom highlighting for numbers, etc. I guess evil-goggles should have own face, by default inherit from the region face. Because some themes have specific settings for the diff/region faces or your users would like to customize only evil-goggles behavior.

```emacs-lisp
(defface evil-goggles-face
  '((t (:inherit region)))
  "Evil-goggles face to use for highlighting different actions."
  :group 'evil-goggles)
```

I could create a PR with this change, but I doubt that only one face is enough, because we have many different actions. So I think there is possible solutions: 

1. Add a general face, which will use for any kind of action.
2. Four evil-goggles faces, which will highlight the following actions: yank, add, delete, change a region. Maybe one extra face for a action like pasting.

**Comment by edkolev** [comment]
This seems like a good addition as a first step - a new face which will by default inherit from 'region. I would gladly accept such a PR.

I'll also think about the rest of the faces, maybe every action should have 2 custom vars - one for on/off toggling, and one for the face (by default inheriting from the common goggles face). I'll think a bit more about this, I don't really like the alists that are used now.

At this point I'm ok with making aggressive customization changes because the package hasn't been announced anywhere yet.

**Comment by 0rdy** [comment]
Presumably there is no reason to let user specify alist, because he can use inheritance or even remap  the built-it evil-goggles faces at any time.

In my opinion, we can add a evil-goggles face(based on the default face) per action and custom boolean variable, which will disable that face. Something like evil-goggles-[action]-face and evil-goggles-hl-action, by default is t .

So user can disable some evil-goggles faces via setq and also customize them in his config. For example:
```emacs-lisp
(setq evil-goggles-hl-yanked nil)
(setq evil-goggles-hl-added nil)

(custom-theme-set-faces
   'theme-name
   '(evil-goggles-face ((t (:inherit highlight))))
   '(evil-goggles-changed-face ((t (:background "yellow")))))
```

**Comment by edkolev** [comment]
As you proposed, each action now has its own face and on/off variable. The naming of the variables is slightly different from your suggestion - the README has up-to-date examples.

Thank you for this suggestion, and please let me know if you think anything else could be improved.
