### ISSUE TITLE
different timeouts for different commands

### ISSUE THREAD

**Issue by wbolster** [edkolev/evil-goggles#6]
when pasting text it helps if the overlay would disappear a little bit slower than it does for e.g. `evil-delete`.

right now this is a single global number.

**Comment by wbolster** [comment]
now that #7 has seen some progress, i think this makes sense:

* one timeout for "before" style overlays, defaulting to e.g. 0.2 seconds (short)
* one timeout for "after" style overlays, defaulting to e.g. 2 seconds (long)

**Comment by edkolev** [comment]
Hey, the following options are now available with https://github.com/edkolev/evil-goggles/commit/be3acc9:
```emacs-lisp
(setq evil-goggles-blocking-duration 0.200) ;; "before" overlays
(setq evil-goggles-async-duration 2.00) ;; "after" overlays
```

Please let me know if they work for you.

**Comment by wbolster** [comment]
i just gave this a try and it seems to work fantastically well. :)

tiny thing... the docstrings of both variables mention:

> This affects the hints which are displayed before the operation.

while one of them is for ‘before’, and the other one for ‘after’.

**Comment by wbolster** [comment]
i'm closing this issue since i consider it resolved!

**Comment by edkolev** [comment]
Thanks and thanks for catching the silly docstrings! I've clarified them a bit in https://github.com/edkolev/evil-goggles/commit/c515477fd4ab46f688123c37c66f209bee081583

There's one experimental feature that I've been excited about myself - pulsing the hint instead of just showing and hiding. In case this interests you, I would appreciate any feedback. The feature is enabled like so:

```
(setq evil-goggles-pulse t)
```

This looks well in GUI emacs, but not in the terminal I think.

**Comment by edkolev** [comment]
Could you please check you have the latest version? I fixed this issue 3-4 days ago in https://github.com/edkolev/evil-goggles/commit/04b93b8564177c9da6366a6db3c6daf8e03e2bcb

**Comment by wbolster** [comment]
ah yes, that changed the behaviour. with timeout of 2 seconds it's not so fluent but in general i like it!
