### ISSUE TITLE
highlight region after operation, not before

### ISSUE THREAD

**Issue by wbolster** [edkolev/evil-goggles#7]
for some operations like filling, shifting, and other "transformative" operations (as opposed to "destructive" operations like `evil-delete`, or "constructive" operations such as `evil-paste-*`), it makes sense to show a highlight _after_ the transformation, instead of showing the region _before_ the transformation.

for example `gqip` to fill a paragraph of text currently has a delay before the result is visible. it would make more sense to highlight the result of the operation instead of its input.

is this something you think is feasible?

**Comment by edkolev** [comment]
Yes, operations like paste only make sense to be visualised after the operation is done (there's nothing meaningful to highlight before any text has been pasted).

Implementing this behaviour is very operation dependant, for example, pasted text can be highlighted only because `evil-paste-before` stores the `beg` and `end` of the pasted text in 2 global variables; evil-goggles then highlights that region.

But unless `evil-fill-and-move` (bound to `gq` by default) has a way to report what is the region after it's done its job, evil-goggles doesn't know what to highlight.

**Comment by edkolev** [comment]
Actually, there might be a way to achieve this by using emacs' `after-change-functions`/ `before-change-functions`, without relying on evil's commands to have a way to report what changed.

**Comment by wbolster** [comment]
@edkolev cak you please reopen this issue? i do not see why it has been closed, and it makes it very hard to keep track.

**Comment by wbolster** [comment]
if you want to organise issues, please add labels instead of closing. thanks! :)

**Comment by edkolev** [comment]
Sure, I'll reopen :)

**Comment by wbolster** [comment]
@edkolev this issue is still closed while it should be open  `</nudge>` ;)

**Comment by edkolev** [comment]
Hm, sorry, I thought I had reopened it.

**Comment by edkolev** [comment]
I finally figured out how to implement this - add an invisible overlay, tweak the overlay so that it grows or shrinks with the text it's over, call the evil command (e.g. indent), make the overlay visible.

Thank you for suggesting this, I think the behaviour of `gqip` makes more sense now.

**Comment by wbolster** [comment]
i just gave this a quick test drive and i love it!

**Comment by wbolster** [comment]
it should also work like this for `evil-shift-left` and `evil-shift-right`, and perhaps others.

**Comment by edkolev** [comment]
Glad you like it.

Regarding shift left/right - these seem to be line-based (`:type line`) so the highlighted region would always be the whole like (if you use `> >`) or the whole paragraph if you use (`> a p`).

In other words, the whole range would be highlighted, from the very start of the first line to the very end of the last line, no matter if we highlight before or after, it's the same either way.

**Comment by wbolster** [comment]
highlighting before interrupts the flow: i press a button and nothing happens until after the delay  (or my next keypresss if i'm impatient).

highlighting after is awesome: you see what you just did. this is also very helpful for others looking at your screen (pair programming) since they have a much better idea what you're doing. in fact this is why i like evil-goggles so much: it makes my "magic" editing operations much more visible, not just to me (which helps me to spot mistakes like wrong motions) but also to others.

**Comment by edkolev** [comment]
Hey, you're absolutely right, I don't know why I didn't see your point earlier, maybe because I use a too low highlight duration.

I'll think about configurable durations per command next.

**Comment by edkolev** [comment]
Since this was proposed, I've modified almost every operation to have a hint displayed after the operation.

Delete is the most noticeable operation which has "before" hint, but it doesn't make sense to show the hint after, since there's no text after deletion :)

Anyway, thanks for suggesting this!

**Comment by wbolster** [comment]
yw, thanks for implementing it. i have used `evil-goggles` for hundreds of hours now and i can only conclude this is a great enhancement to my modal editing flow.
