### ISSUE TITLE
goggles is awesome

### ISSUE THREAD

**Issue by wbolster** [edkolev/evil-goggles#8]
i think this package has a lot of potential to make vim-style editing with evil even more powerful than it already is.

that's why i just blurt out ideas and thoughts in this bug tracker.

keep up the good work. ;)

**Comment by edkolev** [comment]
Glad you like it. Ideas for improvement are more than welcome!

**Comment by thiagowfx** [comment]
I second this. It's so awesome I even want to use something similar to it in vim. Do you know any vim plugin that emulates this behavior?

**Comment by thiagowfx** [comment]
By the way, here is another related question: is there anything similar to this project to use with evil while it is in the emacs mode?

**Comment by edkolev** [comment]
> Do you know any vim plugin that emulates this behavior?

I'm not aware of any. Here you can see a discussion about this in /r/vim:
https://www.reddit.com/r/vim/comments/6qlo9u/is_there_a_vim_plugin_that_does_this/

> is there anything similar to this project to use with evil while it is in emacs mode?

Anything which works for emacs should do. Here are some that I know:
- https://github.com/thierryvolpiatto/zop-to-char doesn't do much but does its job it very well
- https://github.com/k-talo/volatile-highlights.el seems like a "framework" that you can tweak; I don't know how stable/functional it is.

If you want to go outside of the emacs world, I would recommend this editor http://kakoune.org/ which is what inspired me to make evil-goggles. With kakoune you would press `w d` to delete a word, rather than `d w`; you get immediate visual feedback what `w` targets before even deleting with `d`.

**Comment by thiagowfx** [comment]
Thanks for your very complete answer! I will check these out.
